recurly/recurly-client-go

README.md
client.go
client_operations_test.go
client_response.go
client_test.go
error_test.go
recurly_test.go
resources.go

Implement `Count()` for pagers. `First()` and `Take()` will come in a follow up as they will require some refactoring.

Implement Pager.Count()

---

.bumpversion.cfg
.github_changelog_generator
scripts/bump
scripts/changelog
scripts/prepare-release
scripts/release
version.go

Adds the full suite of scripts. Also bumping version to 3.0.0.

Add some more scripts and bump to 3.0.0

---

.bumpversion.cfg
version.go

* Add version scoped url to go.mod and install instructions #30

Release 3.0.1

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.0.1...HEAD)
- Latest Features [\#34](https://github.com/recurly/recurly-client-go/pull/34) ([bhelx](https://github.com/bhelx))
- Add three\_d\_secure\_action\_token\_id  to TransactionError [\#32](https://github.com/recurly/recurly-client-go/pull/32) ([YevheniiGera](https://github.com/YevheniiGera))
- Dont use absolute path to go bin in scripts [\#35](https://github.com/recurly/recurly-client-go/pull/35) ([bhelx](https://github.com/bhelx))
- Fix pagination example [\#33](https://github.com/recurly/recurly-client-go/pull/33) ([bhelx](https://github.com/bhelx))

Release 3.1.0

---

client_operations.go
openapi/api.yaml
requests.go
resources.go

- Adds `preview_subscription_change` operation.
- Adds `AddOnSource` field to `SubscriptionAddOnCreate` and `SubscriptionAddOn`.

Wed Jul  1 02:12:15 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.2.0...HEAD)
- Wed Jul  1 02:12:15 UTC 2020 Upgrade API version v2019-10-10 [\#41](https://github.com/recurly/recurly-client-go/pull/41) ([douglasmiller](https://github.com/douglasmiller))

Release 3.3.0

---

openapi/api.yaml
requests.go

- Adds `AddOnSource` to `SubscriptionAddOnUpdate`

Mon Jul  6 14:54:37 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.3.0...HEAD)
- Mon Jul  6 14:54:37 UTC 2020 Upgrade API version v2019-10-10 [\#43](https://github.com/recurly/recurly-client-go/pull/43) ([douglasmiller](https://github.com/douglasmiller))

Release 3.4.0

---

client_operations.go
openapi/api.yaml
requests.go
resources.go

* Usage and measured units support
* Added `InvoiceCollection` to response for `CreateSubscriptionChange`
* Support `AddOnType` on addons

Latest Changes for 2019-10-10 (usage, measured units, etc)

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.4.0...HEAD)
- Latest Changes for 2019-10-10 \(usage, measured units, etc\) [\#45](https://github.com/recurly/recurly-client-go/pull/45) ([bhelx](https://github.com/bhelx))

Release 3.5.0

---

client.go
client_operations.go
resources.go

Providing an interface for the Client struct for testing purposes.
```go
// MockClient will be our fake client that implements recurly.ClientInterface
type MockClient struct {
}
// we need to implement each method in the interface
func (c *MockClient) CreateAccount(request *recurly.AccountCreate) (*recurly.Account, error) {
// we can setup fake scenarios here depending on the input
// this scenario is hypothetical but it demonstrates that you can use input based rules, or state on the MockClient struct
// to control the behavior of the client for your testing scenarios
if *request.Code == "good" {
// if the account code in our body is "good" we can just return a mock account
account := &recurly.Account{
Id:   "abc123",
Code: *request.Code,
}
return account, nil
} else {
// if the account …
```

Provide interface for testing

---

openapi/api.yaml
requests.go
resources.go

- Adds Custom Fields to the Subscription Change and Subscription Change Preview endpoints.

Mon Aug 31 19:36:28 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.6.0...HEAD)
- Mon Aug 31 19:36:28 UTC 2020 Upgrade API version v2019-10-10 [\#51](https://github.com/recurly/recurly-client-go/pull/51) ([douglasmiller](https://github.com/douglasmiller))
- Code of Conduct [\#50](https://github.com/recurly/recurly-client-go/pull/50) ([bhelx](https://github.com/bhelx))

Release 3.7.0

---

client.go
client_operations.go
client_operations_test.go
client_test.go
recurly_test.go

Reverts recurly/recurly-client-go#21 This should not have gone to master

Revert "Ensure that path parameters are not empty strings"

---

client_operations.go
openapi/api.yaml
requests.go
resources.go

* Adds `GetExportDates` and `GetExportFiles` operations for the [Automated Exports](https://developers.recurly.com/api/v2019-10-10/index.html#tag/automated_exports) feature.
* Adds `ExportDates`, `ExportFiles`, and `ExportFile` resource structs to support the `Automated Exports` feature.
* Adds `BulkCouponCode` and `BulkCouponId` attributes to the `UniqueCouponCode` and `Coupon` resource structs.
* Adds `UnitAmount` and `UsagePercentage` attributes to the `Usage` resource struct.

Latest Changes for 2019-10-10 (Automated Exports, additional resource data attributes)

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.7.0...HEAD)
- Latest Changes for 2019-10-10 \(Automated Exports, additional resource data attributes\) [\#56](https://github.com/recurly/recurly-client-go/pull/56) ([douglasmiller](https://github.com/douglasmiller))
- Ensure that path parameters are not empty strings [\#21](https://github.com/recurly/recurly-client-go/pull/21) ([douglasmiller](https://github.com/douglasmiller))
- Revert "Ensure that path parameters are not empty strings" [\#53](https://github.com/recurly/recurly-client-go/pull/53) ([douglasmiller](https://github.com/douglasmiller))

Release 3.8.0

---

client_operations.go
openapi/api.yaml

* Adds `RestoreCoupon` operation.

Mon Oct 19 20:43:56 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.8.0...HEAD)
- Mon Oct 19 20:43:56 UTC 2020 Upgrade API version v2019-10-10 [\#61](https://github.com/recurly/recurly-client-go/pull/61) ([douglasmiller](https://github.com/douglasmiller))
- Splitting up large files into many smaller files [\#60](https://github.com/recurly/recurly-client-go/pull/60) ([douglasmiller](https://github.com/douglasmiller))

Release 3.9.0

---

billing_info.go
billing_info_create.go
client_operations.go
coupon.go
coupon_create.go
error_types.go
invoice.go
invoice_collect.go
openapi/api.yaml
scripts/clean
subscription.go
subscription_update.go

* `Wallet` features:
* Adds operations for the `Wallet` feature of Recurly API:
* `CreateBillingInfo`
* `ListBillingInfos`
* `GetABillingInfo`
* `UpdateABillingInfo`
* `RemoveABillingInfo`
* Adds `PrimaryPaymentMethod` property to the `BillingInfo` resource and `BillingInfoCreate` request.
* Adds `BillingInfoId` property to the `Invoice` and `Subscription` resources and the `InvoiceCollect` and `SubscriptionUpdate` requests.
* `Item Coupons` features:
* Adds `AppliesToAllItems` and `Items` properties to the `Coupon` resource.
* Adds `AppliesToAllItems` and `ItemCodes` properties to the `CouponCreate` request.
* Adds `ErrorTypeServiceNotAvailable` error type.

Latest Changes for 2019-10-10 (Wallet, Item Coupons)

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.9.0...HEAD)
- Latest Changes for 2019-10-10 \(Wallet, Item Coupons\) [\#65](https://github.com/recurly/recurly-client-go/pull/65) ([douglasmiller](https://github.com/douglasmiller))
- Updating ErrorTypes and status code based error handling to be generated [\#64](https://github.com/recurly/recurly-client-go/pull/64) ([douglasmiller](https://github.com/douglasmiller))

Release 3.10.0

---

billing_info_create.go
openapi/api.yaml
plan_update.go
subscription_create.go

- Adds `TaxIdentifier` and `TaxIdentifierType` to the `BillingInfoCreate` request struct.
- Removes `AddOns` from the `PlanUpdate` request struct due to being unsupported.

Latest Changes for 2019-10-10 (tax_identifier / tax_identifier_type)

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.10.0...HEAD)
- Latest Changes for 2019-10-10 \(tax\_identifier / tax\_identifier\_type\) [\#72](https://github.com/recurly/recurly-client-go/pull/72) ([douglasmiller](https://github.com/douglasmiller))
- Latest Changes for 2019-10-10 [\#71](https://github.com/recurly/recurly-client-go/pull/71) ([douglasmiller](https://github.com/douglasmiller))
- Minor updates to facilitate 4.x changes [\#68](https://github.com/recurly/recurly-client-go/pull/68) ([douglasmiller](https://github.com/douglasmiller))

Release 3.11.0

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.11.0...HEAD)
- Latest Changes for 2019-10-10 [\#74](https://github.com/recurly/recurly-client-go/pull/74) ([douglasmiller](https://github.com/douglasmiller))
- Adding Context and RequestOptions support [\#69](https://github.com/recurly/recurly-client-go/pull/69) ([douglasmiller](https://github.com/douglasmiller))

Release 3.12.0

---

client_operations.go
coupon_redemption.go
coupon_redemption_create.go
openapi/api.yaml

* Adds `SubscriptionId` field to the `CouponRedemptionCreate` request struct.
* Adds `SubscriptionId` field to the `CouponRedemption` resource struct.

Latest Changes for 2019-10-10

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.12.0...HEAD)
- Latest Changes for 2019-10-10 [\#76](https://github.com/recurly/recurly-client-go/pull/76) ([douglasmiller](https://github.com/douglasmiller))

Release 3.13.0

---

.bumpversion.cfg
README.md
go.mod
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v3.13.0...HEAD)
The 4.x major version of the client pairs with the `v2021-02-25` API version. This version of the client and the API contain breaking changes that should be considered before upgrading your integration.
All changes to the core API are documented in the [Developer Portal changelog](https://developers.recurly.com/api/changelog.html#v2021-02-25---current-ga-version)
- Empty path parameters are now explicitly invalid and cause an error to be returned.  [#67] [#68]
- `Params` has been removed in favor of `Context`/`RequestOptions`.  [#70]
```go
headers := http.Header{"Accept-Language": []string{"fr"}}
accountReq := &recurly.AccountCreate{
Params: recurly.Params{
Header: headers,
},
}
account, err := …
```

Release 4.0.0

---

.bumpversion.cfg
version.go

[Full Changelog](https://github.com/recurly/recurly-client-go/compare/v4.0.0...HEAD)
- Generated Latest Changes for v2021-02-25 [\#90](https://github.com/recurly/recurly-client-go/pull/90) ([recurly-integrations](https://github.com/recurly-integrations))
- Export optionsApplier as OptionsApplier [\#81](https://github.com/recurly/recurly-client-go/pull/81) ([jguidry-recurly](https://github.com/jguidry-recurly))

Release 4.0.1
